[project]
name = "lang-chain-course-exp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sivahere4cloud", email = "sivaganeshcloud@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "black>=26.5.1",
    "isort>=9.0.1",
    "langchain>=1.4.2",
    "langchain-openai>=1.6.6",
    "python-dotenv>=1.2.3",
]

[project.scripts]
lang-chain-course-exp = "lang_chain_course_exp:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
